---
title: 'Modeling Multi-pathogen Infectious Disease Systems: Evaluating Statistical
  Methods for Modeling Susceptibility Over Time'
author: "Nicholas G Reich, et al."
date: "April 29, 2015"
output: pdf_document
---


# Abstract

# Introduction

Epidemics of communicable diseases place a huge burden on public health infrastructures across the world. Advanced warnings of increases in disease incidence can help public health authorities allocate resources more effectively and mitigate the impact of epidemics. In some settings, multiple different pathogens or multiple strains of a single pathogen compete to infect susceptible individuals in a population. This competition can drive systems into complex and chaotic dynamics [Rohani?]. Observed data from these multi-pathogen systems has proved difficult to analyze effectively and efficiently, due in large part to the complexity of the interactions between pathogens. 

Infectious disease dynamics at the population level are driven by the aggregate interactions of susceptible and infectious individuals. These interactions are often represented using compartmental models, such as the Susceptible - Infectious - Recovered, or SIR, model. These theoretical models of disease transmission allow an individual in a population to be in one state at any particular time and define possible individual paths through the disease system. 

A central challenge in fitting observed data to any theoretical model of infectious disease transmission is accurately estimating the largely unobservable population of individuals who are susceptible to infection. This challenge is intensified in systems with multiple pathogens, where cross-reactivity (e.g. temporary cross-immunity or antibody dependent enhancement) may directly impact susceptibility. 

Compartmental models of disease spread may be represented mathematically by differential equations, and have been for close to 100 years [Kermack McKendrick]. By studing different possible parameterizations of these models, either numerically (via simulation) or theoretically, we may gain insights into the complex dynamics of real-world disease systems. 

A number of recent papers have succeeded in drawing inference about parameters that govern single-pathogen systems [Shrestha, Ferrari, King, Weitz, ...]. However extending these frameworks to settings with multi-pathogen, multivariate time-series data has proven difficult. Some work has shown through simulation studies that cross-reactive interactions in multi-pathogen systems may give rise to these complex dynamics [@Koelle:2006kf; others from Reich TSIR paper]. And very few published papers in the literature have presented results from fitting multi-pathogen models to real (i.e. not simulated) multi-pathogen time-series data [Reich, Shrestha, Goldstein, ...].

In this manuscript, we will present and analyze three different statistical approaches that may be used to infer the susceptible fraction from aggregate time-series data and incorporate these estimates of population susceptibility into models of disease transmission. We provide an overview of the three models discussed in Table 1, listed top to bottom in order of decreasing biological and computational complexity.

The first approach provides a method to fit data to a complex underlying SIR model. This framework uses sequential Monte Carlo and particle filtering approaches described in detail elsewhere. Fitting this model with this computational framework would require extensive computational time as well as human time to monitor interim results and make adjustments. The second approach extends the TSIR methodology proposed by Finkenstadt and Grenfell (2000) to account for multi-pathogen dynamics. This approach sacrifices some biological complexity to make the model more computationally tractable using either Markov Chain Monte Carlo (MCMC) or a two-stage analysis with Generalized Linear Models (henceforth "two-stage GLM"). Our group has published analyses using this method, and is continuing work to develop and fit models using this framework. The third approach is the simplest and fasted of any of the methods proposed. It uses a simply calculated covariate, a "memory" term, to approximate a measure of susceptibility in the population. This approach uses a simple GLM.

In comparing the characteristics and performance of these three methods side-by-side, we define the scope of the strengths and weaknesses of each of the approaches and identify areas where future work would yield the strongest gains for modelers. 

```{r table1, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
require(pander)
panderOptions('table.split.table', Inf)
set.caption("Overview of methods for fitting four-pathogen models.")

tab1 <- "
model  | method             | runtime    | $p$     | $\\beta(t)$   | $\\delta$      | $\\chi$       
SIR    | particle filtering | 1-6 months | >100    | $\\checkmark$ | $\\checkmark$   | $\\checkmark$  
TSIR   | two-stage GLM      | 1 day      | 30-60   | $\\checkmark$ | $\\checkmark$   | ($\\checkmark$)  
memory | GLM                | 1 minute   | <10     | $\\checkmark$ | ($\\checkmark$) |                
"
df <- read.delim(textConnection(tab1),header=FALSE,sep="|",strip.white=TRUE,stringsAsFactors=FALSE)
names(df) <- unname(as.list(df[1,])) # put headers on
df <- df[-1,] # remove first row
row.names(df)<-NULL
pander(df, style = 'rmarkdown')

```





Additionally, I will propose a new approach to accounting for the susceptible population over time based on observed case data. This method provides a simple way to include complex dynamics in otherwise standard statistical time-series models. Using over four decades of surveillance data on dengue fever infections from the Ministry of Public Health in Thailand, I will illustrate the ability of these methods to draw inference about mechanistic disease transmission models and predict the future spread of disease.

Many infectious diseases are directly transmitted from infectious to susceptible individuals.  



A classic formulation of infectious disease dynamics assumes that the number of new infectious individuals at time $t$ has a non-linear relationship with the number of infectious individals and susceptible individuals at the previous time step. 

Using SIR-style models of disease transmission to estimate parameters of interest has been an active area of research for decades. One of the central challenges faced by all statistical approaches for analyzing this type of data is the inherent difficulty in observing the susceptible population. In a limited set of special cases (e.g. an outbreak in a closed population), the susceptible population may be known exactly. But more commonly, in the ever-changing populations of countries, states, provinces, etc..., it can be very difficult to ascertain directly the fraction of the population that is susceptible to disease at any given time. Yet, to fit something that approximates the "true" model to observed data, susceptibility must be included or estimated in the model fitting procedure. 

In the past few decades, several frameworks for analyzing time-series data from these systems have been proposed, each with a different method for including and/or estimating susceptibility. An early example was the time-series SIR model [Finkenstadt and Grenfell], which used XXX. More recently, a framework for estimation of partially observed Markov processes [cite King et al] uses particle filtering and sequential monte carlo techniques to estimate susceptibility., and an endemic-epidemic framework [Held et al.], to name a few.  



Complex mechanistic models of disease systems require computationally intensive algorithms to fit to real data, and can have prohibitively long computation time [cite sourya]. Simpler more phenomenological models for the disease process can often be fitted to data using less intensive statistical methods. But these simple methods may suffer from bias (since the disease model may not be accurately specified) and may not appropriately account for all of the uncertainty and noise in the disease system. Finding the right balance of model complexity so that these models are conceptually and computationally tractable while remaining faithful to the biological system in question is an area of research that remains largely unexplored.[[cite fisheries pubs from grant]] Work in this area could have a large impact in infectious disease modeling research and potentially in other fields that generate multivariate time series data with complex interactions.

One prominent example of a multi-pathogen disease system is dengue fever, a mosquito-borne arbovirus that infects an estimated 400 million individuals worldwide each year [TSIR 9]. The dengue virus has four identifiable serotypes. Infection with one serotype is thought to confer permanent immunity to that serotype and temporary cross-protection against infection with other serotypes.[Sabin 1952, Reich 2013] However after this temporary protection wanes, individuals are thought to be at increased risk of severe disease when infected with a different serotype.[burke et al 1988] In recent years there has been a substantial increased interest in using infectious disease models to understand interactions between pathogens. [TSIR grant citations: 15,16,22-28] Some of this research on the dynamics of dengue in different geographical locations has demonstrated that complex dynamics observed in data are consistent with the presence of cross-protection and immune enhancement [more citations].  However, very few research teams have used data to explicitly estimate characteristics such as cross-protection or immune enhancement. 



# 